apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-pv
spec:
  capacity:
    storage: 999Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  local:
    path: /run/desktop/mnt/host{{.Values.persistence.config.winPath}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
