apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.sonarr.existingClaim }}
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 999Gi
