apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-dav-pv
spec:
  capacity:
    storage: 999Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.persistence.webdav.existingClaim }}
  storageClassName: ""
  nfs:
    server: {{ .Values.persistence.webdav.davUrl }}
    path: {{ .Values.persistence.webdav.davPath }}
