annotations:
  truecharts.org/SCALE-support: "true"
  truecharts.org/catagories: |
    - media
  truecharts.org/grade: U
apiVersion: v2
appVersion: 3.0.9.1549
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 11.1.2
description: Smart PVR for newsgroup and bittorrent users
home: https://truecharts.org/charts/stable/sonarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sonarr.png
keywords:
- sonarr
- torrent
- usenet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: sonarr
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/sonarr
- https://ghcr.io/onedr0p/sonarr
- https://github.com/Sonarr/Sonarr
type: application
version: 13.0.8
