image:
  repository: ghcr.io/onedr0p/sabnzbd
  pullPolicy: IfNotPresent
  tag: 4.3.2@sha256:8e70a877c77805dfe93ce30a8da3362fbddf221ef806951d4e4634bb80dc87b5
exportarrImage:
  repository: ghcr.io/onedr0p/exportarr
  pullPolicy: IfNotPresent
  tag: v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
service:
  main:
    type: NodePort
    ports:
      main:
        port: 8989
        targetPort: 8989
        nodePort: 30448
  metrics:
    enabled: true
    type: ClusterIP
    targetSelector: exportarr
    ports:
      metrics:
        enabled: true
        port: 8990
        targetSelector: exportarr
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SABNZBD__HOST_WHITELIST_ENTRIES: ""
            SABNZBD__PORT: "{{ .Values.service.main.ports.main.port }}"
  exportarr:
    enabled: "{{ .Values.metrics.main.enabled }}"
    type: Deployment
    strategy: RollingUpdate
    replicas: 1
    podSpec:
      containers:
        exportarr:
          primary: true
          enabled: true
          imageSelector: exportarrImage
          args:
            - sabnzbd
          probes:
            liveness:
              enabled: true
              type: http
              path: /healthz
              port: "{{ .Values.service.metrics.ports.metrics.port }}"
            readiness:
              enabled: true
              type: http
              path: /healthz
              port: "{{ .Values.service.metrics.ports.metrics.port }}"
            startup:
              enabled: true
              type: http
              path: /healthz
              port: "{{ .Values.service.metrics.ports.metrics.port }}"
          env:
            INTERFACE: 0.0.0.0
            PORT: "{{ .Values.service.metrics.ports.metrics.port }}"
            URL: '{{ printf "http://%v:%v" (include "tc.v1.common.lib.chart.names.fullname" $) .Values.service.main.ports.main.port }}'
            APIKEY: "{{ .Values.metrics.main.apiKey }}"

persistence:
  config:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: "/config"
          pvNames: son
          winPath: /c/sonarr
      exportarr:
        exportarr:
          mountPath: /config
          readOnly: true
  sabnzbd:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: "/sabnzbd"
          pvNames: sab
          winPath: /c/sabnzbd
metrics:
  main:
    enabled: false
    type: "servicemonitor"
    endpoints:
      - port: metrics
        path: /metrics
    targetSelector: metrics
    # Required for exportarr
    apiKey: ""

portal:
  open:
    enabled: true