annotations:
  truecharts.org/SCALE-support: "true"
  truecharts.org/catagories: |
    - media
apiVersion: v2
appVersion: 4.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 12.8.1
description: Free and easy binary newsreader
home: https://truecharts.org/charts/stable/sabnzbd
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sabnzbd.png
keywords:
- sabnzbd
- usenet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: sabnzbd
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/sabnzbd
- https://sabnzbd.org/
type: application
version: 14.0.15
