image:
  repository: tccr.io/truecharts/sabnzbd
  pullPolicy: IfNotPresent
  tag: 3.7.2@sha256:a1534066289240c3c3968e3a95999b47534dd706f5997d42b4cfdd098eb9b475

env:
  SABNZBD__HOST_WHITELIST_ENTRIES: ""

service:
  main:
    type: NodePort
    ports:
      main:
        port: 10097
        targetPort: 8080
        nodePort: 30447

persistence:
  config:
    enabled: true
    mountPath: "/config"
    existingClaim: sabnzbd-pvc
    winPath: /c/sabnzbd

portal:
  enabled: true
