image:
  repository: tccr.io/truecharts/sabnzbd
  pullPolicy: IfNotPresent
  tag: v4.0.1@sha256:e360b8faa51d47bbcea9d18e11de417f9dbbf09f2e3b73c415e67fa43f4e6473
service:
  main:
    type: NodePort
    ports:
      main:
        port: 10097
        targetPort: 8080
        nodePort: 30447

persistence:
  config:
    enabled: true
    mountPath: "/config"
    existingClaim: sabnzbd-pvc
    winPath: /c/sabnzbd

portal:
  open:
    enabled: true

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SABNZBD__HOST_WHITELIST_ENTRIES: ""
