image:
  repository: tccr.io/truecharts/jellyfin
  pullPolicy: IfNotPresent
  tag: 10.8.9@sha256:32efce54017dcefcd437dc179baabb0ed79ad44298b9d0850388bd69f8e9eac5

securityContext:
  readOnlyRootFilesystem: false

env:
  JELLYFIN_PublishedServerUrl: "https://jelly.mydomain.com"

service:
  main:
    type: NodePort
    ports:
      main:
        port: 8096
        targetPort: 8096
        nodePort: 30445

persistence:
  config:
    enabled: true
    mountPath: "/config"
    existingClaim: jellyfin-config-pvc
    winPath: /c/jellyfin/config
  cache:
    enabled: true
    mountPath: "/cache"
    type: "emptyDir"
    existingClaim: jellyfin-cache-pvc
    winPath: /c/jellyfin/cache
  transcode:
    enabled: true
    mountPath: "/config/transcodes"
    type: "emptyDir"
  sonarr:
    enabled: true
    mountPath: "/sonarr"
    existingClaim: jellyfin-son-pvc
    winPath: /c/sonarr
  radarr:
    enabled: true
    mountPath: "/radarr"
    existingClaim: jellyfin-rad-pvc
    winPath: /c/radarr

portal:
  enabled: true
