apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.sabnzbd.pvNames }}-pv
spec:
  capacity:
    storage: 999Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.persistence.sabnzbd.pvNames }}-pvc
  storageClassName: hostpath
  local:
    path: /run/desktop/mnt/host{{.Values.persistence.sabnzbd.winPath}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
