apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.sabnzbd.targetSelector.main.main.pvNames }}-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 999Gi
